#!/bin/sh
#
#-----------------------------------------------------------------------------------
####################################################################################
# Warning! Don't change the following text, if you don't know what are you doing.
# Предупреждение! Не изменяйте следующий текст, если не знаете что делаете.
####################################################################################
#-----------------------------------------------------------------------------------
#
DIRNAME=$(dirname $0)
. $DIRNAME/conf/mysql.cfg

if [ "$port" ]
then
	port="--port=$port"
fi

cd ${DIRNAME}/../../
mysql -u $user --password=$pass -h $host $port -B $dbname < shema.sql
mysql -u $user --password=$pass -h $host $port -B $dbname < db.sql

echo "The database $dbname@$host has been updated"

exit 0
