#!/bin/sh
#
#  Copyright 2013  Konstantin Slupko (email: linux0uid@gmail.com)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#-----------------------------------------------------------------------------------
####################################################################################
# Warning! Don't change the following text, if you don't know what are you doing.
# Предупреждение! Не изменяйте следующий текст, если не знаете что делаете.
####################################################################################
#-----------------------------------------------------------------------------------
#
DIRNAME=$(dirname $0)
. $DIRNAME/conf/mysql.cfg

if [ "$port" ]
then
	port="--port=$port"
fi

cd ${DIRNAME}/../../
mysql -u $user --password=$pass -h $host $port -B $dbname < shema.sql
mysql -u $user --password=$pass -h $host $port -B $dbname < db.sql

echo "The database $dbname@$host has been updated"

exit 0
