#!/bin/sh
#
#  Copyright 2014  Konstantin Slupko (email: linux0uid@gmail.com)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#-----------------------------------------------------------------------------------
####################################################################################
# Warning! Don't change the following text, if you don't know what are you doing.
# Предупреждение! Не изменяйте следующий текст, если не знаете что делаете.
####################################################################################
#-----------------------------------------------------------------------------------
#
DIRNAME=$(dirname $0)
. $DIRNAME/conf/db.conf
REALDIRNAME=$(dirname $(readlink -e $0))

cd ${DIRNAME}/../../
PROGECTDIRNAME=$(pwd);

#Check using drush
if [ "$use_drush" = "yes" ]; then

    drush variable-set -y maintenance_mode 1
    ERROR=$?
    if [ "$ERROR" -ne 0 ]
    then
        echo "
            Warning! You do not have drush or it is not working correctly.
            Install the drush, please!!!"
    else
        `drush sql-connect` < db.sql
    fi
    drush variable-delete -y maintenance_mode 0

else

    if [ "$port" ]
    then
    	port="--port=$port"
    fi

    mysql -u $user --password=$pass -h $host $port -B $dbname < db.sql
    
    if [ "$?" -eq 0 ]
    then
    	echo "The database $dbname@$host has been successfully updated"
    else
    	echo "
    		-----------------!!!ERROR!!!----------------
    		Database $dbname@$host has NOT been updated
    		You're doing something wrong!!!
    		
    		Check your config file: $REALDIRNAME/conf/db.conf
    		Check the availability and accuracy of the following files:
    		$PROGECTDIRNAME/db.sql"
    fi

fi


exit 0
