#!/bin/sh
#
#-----------------------------------------------------------------------------------
####################################################################################
# Warning! Don't change the following text, if you don't know what are you doing.
# Предупреждение! Не изменяйте следующий текст, если не знаете что делаете.
####################################################################################
#-----------------------------------------------------------------------------------
#
DIRNAME=$(dirname $0)
. $DIRNAME/conf/mysql.cfg

if [ "$port" ]
then
	port="--port=$port"
fi

cd ${DIRNAME}/../../
mysqldump -u $user --password=$pass -h $host $port -v --no-data --single-transaction --skip-comments --opt --add-drop-database -B $dbname > shema.sql 
mysqldump -u $user --password=$pass -h $host $port -v --single-transaction --skip-comments --opt $dbname > db.sql

echo "Database dump $dbname@$host saved in the file db.sql"

git add db.sql
git add shema.sql

exit 0
