#!/bin/sh
#
#  Copyright 2013  Konstantin Slupko (email: linux0uid@gmail.com)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#-----------------------------------------------------------------------------------
####################################################################################
# Warning! Don't change the following text, if you don't know what are you doing.
# Предупреждение! Не изменяйте следующий текст, если не знаете что делаете.
####################################################################################
#-----------------------------------------------------------------------------------
#
DIRNAME=$(dirname $0)
. $DIRNAME/conf/mysql.cfg
REALDIRNAME=$(dirname $(readlink -e $0))

if [ "$port" ]
then
	port="--port=$port"
fi

cd ${DIRNAME}/../../
mysqldump -u $user --password=$pass -h $host $port --no-data --single-transaction --skip-comments --opt --add-drop-database -B $dbname > shema.sql 

if [ "$?" = "0" ]
then
	echo "Database dump --no-data $dbname@$host saved in the file shema.sql"
else
	echo "
		-----------------------!!!ERROR!!!---------------------------
		Database dump $dbname@$host is NOT saved in the file shema.sql
		You're doing something wrong!!!
		Check your config file: $REALDIRNAME/conf/mysql.cfg"
fi

mysqldump -u $user --password=$pass -h $host $port --single-transaction --skip-comments --opt $dbname > db.sql

if [ "$?" = "0" ]
then
	echo "Database dump $dbname@$host saved in the file db.sql"
else
	echo "
		-----------------------!!!ERROR!!!---------------------------
		Database dump $dbname@$host is NOT saved in the file db.sql
		You're doing something wrong!!!
		Check your config file: $REALDIRNAME/conf/mysql.cfg"
fi

git add db.sql
git add shema.sql

exit 0
